name: CD for my pipeline :)

on: 
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  deploy_code:
    name: Deploy my Great Databricks Pipeline to production
    uses: .github/workflows/reusable_databricks_code_deployment.yml@v1.0.0
    with:
      databricks_code_path: "Pipelines/prod/my_great_pipeline"
      service_code_file: "src/code/pipeline.py"
    secrets:
      DATABRICKS_HOST_URL: adb-3129059325504714.14.azuredatabricks.net
      DATABRICKS_TOKEN: dapif775ef7c53fc0f2ae4b391689b1a44fa-2
