name: Notebook Deployment - Databricks
on:
  workflow_call:
    inputs:
      databricks_code_path:
        description: Databricks Service Path
        type: string
        required: false
      
      service_code_file:
        description: python code file path
        type: string
        required: false


jobs:
  push_to_db:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3.3.0
      
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Databricks CLI config
        uses: microsoft/install-databricks-cli@v1.0.0
    
      - name: databricks-import-directory
        uses: microsoft/databricks-import-directory@v1.0.0
        with:
         databricks-host: https://adb-2994064724248266.6.azuredatabricks.net/
         databricks-token: dapib120c842ee41d8b1f8a3cf72dd22aaff-2
         local-path: ./src/code/Demo.py
         remote-path: /Pipelines/prod/Demo.py
